### ISSUE TITLE
The implementation of  SameModule

### ISSUE THREAD

**Issue by YuanEZhou** [shijx12/XNM-Net#1]
https://github.com/shijx12/XNM-Net/blob/e3e6bb305217949315bbf70f4e01c5c0dbadbb9c/exp_clevr_gt_softmax/model/composite_modules.py#L32

Hi, @shijx12 , Thanks for your released code.  I don't think the implementation of SameModule makes sense.  The declaration of  Same Module in your paper is more convincing.

**Comment by shijx12** [comment]
It is a tricky implementation to regard attributes as special nodes. In the GT softmax setting, since we have known specific attribute values of objects, it is not necessary to learn mapping matrixes. Instead, we directly define and fix them, which is described in details in the appendix.
In fact, my implementation is consistent with the description of my paper. `self.relate` = Describe, and `self.transConn` is a simplified version of AttendNode.

**Comment by YuanEZhou** [comment]
OK. Thanks for your reply.

**Comment by shijx12** [comment]
You are welcome :)
